version: '3.9'

services:
  web:
    build:
      context: ./repos/scs_web
      dockerfile: Dockerfile.dev
    container_name: scs-web
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./repos/scs_web:/app
    user: scs-user

  api:
    build: 
      context: ./repos/scs_api
      dockerfile: Dockerfile.dev
    container_name: scs-api
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - ./repos/scs_api:/app
    user: scs-user
    networks:
      default:
      scancans_shared-network:
        aliases:
          - host.scs-api.internal

networks:
  scancans_shared-network:
    external: true
