version: '3.9'

services:
  api:
    build: 
      context: ./repos/scs_api
      dockerfile: Dockerfile.dev
    container_name: scs-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos/scs_api/src:/app/src
      - ./repos/scs_api/logs:/app/logs:rw
      - ./repos/scs_api/.env:/app/.env:ro
      - ./repos/scs_api/ecosystem.config.js:/app/ecosystem.config.js
    user: scs-user
    networks:
      default:
      scancans_shared-network:
        aliases:
          - host.scs-api.internal

networks:
  scancans_shared-network:
    external: true